<?xml version="1.0" standalone="yes"?>
<!--Generated by SISProjectCreator Version 1.0-->
<Msg>
	<Item>
		<Key>Scope</Key>
		<Value>!scope!</Value>
	</Item>
	<Item>
		<Key>MessageType</Key>
		<Value>Register</Value>
	</Item>
	<Item>
		<Key>Role</Key>
		<Value>Controller</Value>
	</Item>
	<Item>
		<Key>Name</Key>
		<Value>!name!</Value>
	</Item>
</Msg>

